python3 unstable.py \
    --model_name "Qwen/Qwen3-0.6B" \
    --wandb \
    --num_actors 3 \
    --num_learners 1 \
    --lr 1e-4 \
    --batch_size 64 \
    --gradient_accumulation_steps 64 \
    --max_tokens 2048 \
    --gradient_checkpointing \
    --bf16_training \
    --num_collection_workers 128 \
    --num_evaluation_workers 2
