_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
                - 71
                - 98
            "2":
                - 1
                - 2
                - 3
                - 11
                - 41
                - 49
                - 55
                - 71
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.8
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 3
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 32
lora_alpha:
    value: 128
lora_dropout:
    value: 0.03
lora_rank:
    value: 64
lr:
    value: 0.0001
model_name:
    value: Qwen/Qwen3-4B-base
output_dir:
    value: sft_lora_4b
train_files:
    value:
        - data/Snake.jsonl
        - data/SimpleTak.jsonl
        - data/SimpleNegotiation.jsonl
use_rslora:
    value: true
val_file:
    value: null
wandb_name:
    value: combined-sft
wandb_project:
    value: UnstableBaselines
warmup_ratio:
    value: 0.1
