compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
num_processes: 4  # or however many GPUs you're using
mixed_precision: bf16  # or fp16 or no
use_cpu: false
tpu_use_cluster: false
machine_rank: 0
main_process_ip: null
main_process_port: null
tpu_parallel_devices: []
fsdp_config: null
megatron_lm_config:
  tensor_parallel_size: 2
